"""Recreate migrations

Revision ID: dcbbbeb1f071
Revises: 
Create Date: 2025-04-07 17:19:22.817449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = 'dcbbbeb1f071'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('passwords',
    sa.Column('service_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_passwords_id'), 'passwords', ['id'], unique=False)
    op.create_index(op.f('ix_passwords_service_name'), 'passwords', ['service_name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_passwords_service_name'), table_name='passwords')
    op.drop_index(op.f('ix_passwords_id'), table_name='passwords')
    op.drop_table('passwords')
    # ### end Alembic commands ###
